# DESAFIO: "MEGASENA!"

# Quais são as chances de ganhar na Megasena? Podemos escolher de 6 a 20 números, mas para cada número extra, o valor do bilhete aumenta de forma exponencial! 
# Então, não seria melhor saber quais são as minhas chances, para decidir qual será a melhor opção de aposta? Ou ainda, definir quantas apostas fazem sentido!​

def calcular_chances(qtd_numeros):
    if qtd_numeros < 6 or qtd_numeros > 20: # Verificando se a quantdade de números é de 6 a 20...
        print("A quantidade de números deve ser entre 6 e 20.")
        return None # Retornando None para indicar que a entrada é inválida...
    
    total_combinacoes = 60 # Defininddo o total de combinações...
    numeros_escolhidos = qtd_numeros # A quantidade de números escolhidos é igual a qtd_numeros...
    numeros_restantes = total_combinacoes - numeros_escolhidos 
    
    # Cálculo das combinações possíveis
    chances = 1 # Chances inicializadas em 1...
    for i in range(6): # Loop para calcular as chances de ganhar com base na quantidade de números escolhidos...
        chances *= (numeros_restantes - i) / (total_combinacoes - i) # Multiplicando as chances para cada número escolhido...
    
    return chances # Retornando as chances calculadas...
# Exemplo de uso
qtd_numeros = int(input("Digite a quantidade de números que deseja apostar (entre 6 e 20): ")) # Imputando a quantidade de números que deseja apostar...
chances = calcular_chances(qtd_numeros) # Calculando as chances de ganhar na Megasena com a quantidade de números escolhida...
if chances is not None: # Verificando se as chances foram calculadas corretamente...
    print(f"As chances de ganhar na Megasena com {qtd_numeros} números são de aproximadamente {chances:.10f}.") 
