# Calculo da tabela de tabuada...

print("Tabuada!") # imprimindo a palavra "Tabuada!"...
for X in range(1,10): # Loop para calcular a tabuada de 1 a 9...
    for Y in range(1,10): # Loop para calcular a tabuada de 1 a 9...
        Z = X * Y # Z recebe o valor da multiplicação de X por Y...
        print(Z, " ", end=" ") # imprimindo o valor de Z, seguido de um espaço, e mantendo a impressão na mesma linha...
    print(" ") 
        