# 2- ATIVIDADE: Escreva um programa onde o usuário irá digitar 3 números distintos, 
# que por sua vez serão armazenados nas variáveis "X", "Y" e "Z". 
# A partir daí, o programa informe se estes números estão em ordem crescente ou decrescente. 
# Se não, exibir "Eles estão misturados"!​

print("Informe o primeiro número, Por favor!: ")
X = float(input()) # imputando o X...
print("Informe o segundo número, Por favor!:  ")
Y = float(input()) # imputando o Y...
print("Informe o terceiro numero, Por favor!: ")
Z = float(input()) # imputando o Z...

if X < Y < Z: # caso X for menor que Y e menor que Z...
    print("Ordem Crescente!")
elif X > Y > Z: # caso X for maior que Y e maior que Z...
    print("Ordem Decrescente!")
else: # caso os números informados estejam embaralhados...
    print("Eles estão misturados!")
