#Demonstrações de uso de operadores aritméticos...

X = int(input("Digite o valor de X: ")) # imputando o valor de X...
Y = int(input("Digite o valor de Y: ")) # imputando o valor de Y...

SOMAR = X + Y # operação de soma...
print("O resultado da soma:", SOMAR)

SUBTRAIR = X - Y # operaão de subtração...
print("O resultado da subtracao: ", SUBTRAIR)

MULTIPLICAR = X * Y # operação de multiplicação...
print("O resultado da multiplicaçao: ", MULTIPLICAR)

DIVIDIR = X / Y # operação de divisão...
print("O resultado da divisao: ", DIVIDIR)
