# 1- ATIVIDADE: “Construa um programa onde o usuário irá digitar o nome de um filme ou série de TV e em seguida, perguntará qual seria a sua nota para avaliar o filme, em uma escala de 1 a 5. 
# De acordo com a nota definida, o usuário receberá as respostas “Péssimo”, “Ruim”, “Razoável”, “Bom” e “Ótimo”. 
# e em caso de notas baixas, deverá ser feita dado ao usuário, a possibilidade de descrever o porquê do conteúdo em questão foi avaliado de forma negativa. 
# Por fim, caso o usuário digite qualquer outro valor fora da escala, deverá ser exibido um alerta.​


print("\n=== AVALIAÇÃO ===\n")
# Menu
print("1. Péssimo")
print("2. Ruim")
print("3. Razoável")
print("4. Bom")
print("5. Ótimo")

print("Digite um Filme ou Série: ")
MOVIE = input() # imputando nome do filme ou série...

print("Digite uma nota para avaliação: ")
NOTA = float(input()) # imputando nota...

match NOTA: 
    case 1: # caso a nota seja 1 o sistema pedirá uma avaliação mais detalhada...
        print(input("Informe sua sua avaliação:")) # imputando nota 1...
        print("Obrigado pela sua avaliação!")
    case 2:# caso a nota seja 2 o sistema pedirá uma avaliação mais detalhada...
        print(input("Informe a sua avalição: ")) # imputando nota 2...
        print("Obrigado pela sua avaliação!")
    case 3:# caso a nota seja 3 o sistema pedirá uma avaliação mais detalhada...
        print(input("Informe sua avaliação: ")) # imputando nota 3...
        print("Obrigado pela sua avaliação!")
    case 4: # caso a nota seja 4...
        print("Obrigado pela sua avaliação!")
    case 5: # caso a nota seja 5...
        print("Obrigado pela sua avaliação!")
    case _: # caso não seja nenhuma das opcoes do menu...
        print("Nota inválida!")