#3- ATIVIDADE: Construa um programa para que o usuário possa digitar um número 
# e o programa escreverá, na tela, o resultado do quadrado e do cubo do valor já digitado.​

VALOR = int(input("Digite aqui o valor: ")) # imputando valor...

print(VALOR ** 2) # resultando do valor ao QUADRADO...
print(VALOR ** 3) # resultado do valor ao CUBO...