# 3 - ATIVIDADE: Construa um programa onde o usuário irá digitar seu nome e cidade de onde está digitando. 
# Essas informações passarão para uma função e, caso a cidade seja “Rio de Janeiro”, 
# a resposta, além do nome da pessoa, escreverá “Seja Bem-vindo à Cidade Maravilhosa”. 
# Caso contrário, exibirá apenas o nome e a cidade digitada (utilizar passagem de argumentos).

def usuario(nome, estado): # função para avaliar a naturalidade do usuário e exibir a mensagem personalizada correspondente...
    if estado == "Rio de Janeiro": # se a cidade for igual a Rio de Janeiro, o programa exibirá a mensagem personalizada de boas-vindas à Cidade Maravilhosa...
        print(nome)
        print("Seja Bem-vindo à Cidade Maravilhosa.")
    else: # caso contrário, o programa exibirá apenas o nome e a cidade digitada...
        print(nome)
        print(estado)

nome = input("Digite seu nome: ") # imputando o nome do usuário e armazenando na variável "nome"...
estado = input("Digite seu estado: ") # imputando o nome do estado onde o usuário está digitando e armazenando na variável "estado"...

usuario(nome, estado) # chama a função para avaliar a naturalidade do usuário e exibir a mensagem personalizada correspondente...