# 2 - ATIVIDADE: “Criar um programa que exiba os dados cadastrais de um paciente: 
# Nome, data de nascimento, sexo, diagnóstico, estado, tratamento e data de liberação. 
# Este programa deverá possibilitar a alteração dos dados cadastrados e assim, mostrar a ficha atualizada.​

nome = input("Digite o nome do paciente: ") # imputando valor de nome...
nascimento = float(input("Digite a data de nascimento do paciente: ")) # imputando valor de nascimento...
sexo = input("Digite o sexo do paciente: ") # imputando valor de sexo...
diagnostico = input("Digite o diagnóstico do paciente: ") # imputando valor de diagnóstico...
estado = input("Digite o estado do paciente: ") # imputando valor de estado...
tratamento = input("Digite o tratamento do paciente: ") # imputando valor de tratamento...
liberacao = float(input("Digite a data de liberação do paciente: ")) # imputando valor de liberação...

while True: # Loop para permitir alterações nos dados...
    print("\n=== DADOS CADATRAIS ===\n")
    print("Nome: ", nome)
    print("Nascimento: ", nascimento)
    print("Sexo: ", sexo)
    print("Diagnostico: ", diagnostico)
    print("Estado: ", estado)
    print("Tratamento: ", tratamento)
    print("Liberacao: ", liberacao)
    
    alterar = input("Deseja alterar algum dado? (sim/não): ") # Perguntando se o usuário deseja alterar algum dado...
    if alterar.lower() == "sim": # Verificando se a resposta é "sim"
        campo = input("Qual campo deseja alterar? (nome/nascimento/sexo/diagnostico/estado/tratamento/liberacao): ") # Perguntando qual campo deseja alterar...
        if campo.lower() == "nome": # Verificando se o campo é "nome"
            nome = input("Digite o novo nome do paciente: ") # imputando novo valor de nome...
        elif campo.lower() == "nascimento": # Verificando se o campo é "nascimento"
            nascimento = float(input("Digite a nova data de nascimento do paciente: ")) # imputando novo valor de nascimento...
        elif campo.lower() == "sexo": # Verificando se o campo é "sexo"
            sexo = input("Digite o novo sexo do paciente: ") # imputando novo valor de sexo...
        elif campo.lower() == "diagnostico": # Verificando se o campo é "diagnostico"
            diagnostico = input("Digite o novo diagnóstico do paciente: ") # imputando novo valor de diagnóstico...
        elif campo.lower() == "estado": # Verificando se o campo é "estado"
            estado = input("Digite o novo estado do paciente: ") # imputando novo valor de estado...
        elif campo.lower() == "tratamento": # Verificando se o campo é "tratamento"
            tratamento = input("Digite o novo tratamento do paciente: ") # imputando novo valor de tratamento...
        elif campo.lower() == "liberacao": # Verificando se o campo é "liberacao"
            liberacao = float(input("Digite a nova data de liberação do paciente: ")) # imputando novo valor de liberação...
        else:
            print("Campo inválido. Por favor, tente novamente.") # Imprimindo mensagem de erro para campo inválido...
    elif alterar.lower() == "não": # Verificando se a resposta é "não"
        print("Ficha atualizada. Encerrando o programa.") # Imprimindo mensagem de encerramento...
        break
