# 3 - ATIVIDADE: “Criar um programa que possibilite o usuário digitar os 6 números para concorrer na MEGASENA. 
# Obviamente, estes números não poderão ser cadastrados de forma repetida.

numeros = [] # Criando uma lista vazia para armazenar os números...

while len(numeros) < 6: # Loop para permitir a entrada de 6 números...
    numero = int(input("Digite um número para concorrer na MEGASENA (entre 1 e 60): ")) # imputando valor de numero...
    if numero < 1 or numero > 60: # Verificando se o número é menor que 1 ou maior que 60...
        print("Número inválido. Por favor, digite um número entre 1 e 60.") # Imprimindo mensagem de erro...
    elif numero in numeros: # Verificando se o número já foi digitado...
        print("Número repetido. Por favor, digite um número diferente.") # Imprimindo mensagem de erro...
    else:
        numeros.append(numero) # Adicionando o número à lista...
print("Números selecionados para a MEGASENA:", numeros) # Imprimindo os números selecionados para a MEGASENA...
